apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vmrxt9a1o-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:28f1c0d5db8c8c30a1355a989387a7b2afe2fd45@sha256:900fd30561846a42fd06d48a163b2bf5d2a5cc01805fa697fe6af96d8b1ac75e
          name: container-image
